# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: chinadep@123
    driver-class-name: com.mysql.jdbc.Driver

# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.deluxe: debug

mybatis-plus:
  # 扫描 mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    jdbc-type-for-null: 'null'
